---
name: TestFX 4 CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  packages: read
  pull-requests: write
  statuses: read
  security-events: write

jobs:
  #  testfx-4-ubuntu-22-04-jdk-8-jfx-8:
  #    name: TestFX 4 - Ubuntu 22.04 - JDK 8 - JFX 8
  #    uses: ./.github/workflows/build.yml
  #    with:
  #      os: ubuntu-22.04
  #      jdk: 8
  #      openjfx: 8
  #    secrets: inherit
  monocle:
    name: Monocle
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-22.04
      jdk: 17.0.10
      openjfx: 17
    secrets: inherit
