---
name: Monocle CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  packages: read
  pull-requests: write
  statuses: read
  security-events: write

jobs:
  monocle:
    name: Monocle
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-22.04
      jdk: 11
      openjfx: 11
    secrets: inherit
